version: '3.8'

services:
  web:
    image: patilchinu/todoapp:latest
    ports:
      - "5000:5000"
    deploy:
      mode: replicated
      replicas: 3
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: todo
    volumes:
      - db_data:/var/lib/mysql
    deploy:
      placement:
        constraints:
          - node.role == manager

volumes:
  db_data:
