version: '3.8'

services:
  web:
    build: .
    container_name: todo-web
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_USER=todo_user
      - DB_PASSWORD=password
      - DB_NAME=mytododb
    depends_on:
      - db
    networks:
      - todo-net

  db:
    image: mysql:5.7
    container_name: todo-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mytododb
      MYSQL_USER: todo_user
      MYSQL_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - todo-net

networks:
  todo-net:
    driver: bridge

volumes:
  db-data:
