version: '3'
services:
  web:
    image: patilchinu/todoapp:latest
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: todo
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

