version: '3.8'

networks:
  todo-net:
    driver: overlay

services:
  web:
    image: patilchinu/todoapp:latest
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_USER: todo_user
      DB_PASSWORD: password
      DB_NAME: mytododb
    depends_on:
      - db
    networks:
      - todo-net
    deploy:
      replicas: 3
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mytododb
      MYSQL_USER: todo_user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - todo-net
    deploy:
      placement:
        constraints:
          - node.role == manager

volumes:
  db_data:
