version: "3.8"

services:
  web:
    image: patilchinu/todoapp:latest
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_USER: todo_user
      DB_PASSWORD: password
      DB_NAME: mytododb
    networks:
      - todo-net
    deploy:
      replicas: 3

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: mytododb
      MYSQL_USER: todo_user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - todo-net
    deploy:
      placement:
        constraints: [node.role == worker]

networks:
  todo-net:
    driver: overlay

volumes:
  db-data:
